### **What is Object Detection?**

Object detection answers two questions at the same time:
- WHAT is in the image?
- WHERE is it?

Model response like this:

```
[
    {
        class: "person",
        confidence: 0.94,
        box: (120, 80, 300, 400)
    },

    {
        class: "car",
        confidence: 0.91,
        box: (400, 200, 700, 450)
    }
]
```

```
IMAGE
  ↓
Preprocessing
  ↓
MODEL
  ↓
Predictions
  ↓
┌─────────────────────────────┐
│ Person  0.94  [box]        │
│ Car     0.91  [box]        │
│ Dog     0.87  [box]        │
└─────────────────────────────┘

- YOLO predicts numerical values representing boxes, classes, and confidence scores.

| Concept              | Meaning                               |
| -------------------- | ------------------------------------- |
| Classification       | **What** is in the image?             |
| Localization         | **Where** is the main object?         |
| Detection            | **What + where** for multiple objects |
| Bounding box         | Rectangle around an object            |
| `(x1,y1,x2,y2)`      | Box represented by corners            |
| `(x,y,w,h)`          | Box represented by position + size    |
| Class                | Object category                       |
| Confidence           | How confident the model is            |
| Confidence threshold | Removes weak predictions              |


```
                 OBJECT DETECTION
                       │
             ┌─────────┴─────────┐
             ↓                   ↓
           WHAT?               WHERE?
             ↓                   ↓
          Class             Bounding Box
             │                   │
             └─────────┬─────────┘
                       ↓
                  Confidence

In [1]:
import cv2
import numpy as np

# Create a blank image
image = np.zeros((500, 700, 3), dtype=np.uint8)

# Our "detector" says:
x1, y1 = 150, 100
x2, y2 = 450, 400

label = "Person"
confidence = 0.92

# Draw bounding box
cv2.rectangle(
    image,
    (x1, y1),
    (x2, y2),
    (0, 255, 0),
    2
)

# Draw label
text = f"{label} {confidence:.2f}"

cv2.putText(
    image,
    text,
    (x1, y1 - 10),
    cv2.FONT_HERSHEY_SIMPLEX,
    0.7,
    (0, 255, 0),
    2
)

cv2.imshow("Object Detection", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
detections = [
    {
        "class": "person",
        "confidence": 0.92,
        "box": (100, 80, 250, 400)
    },
    {
        "class": "car",
        "confidence": 0.87,
        "box": (350, 200, 650, 420)
    },
    {
        "class": "dog",
        "confidence": 0.76,
        "box": (500, 100, 620, 250)
    }
]

In [3]:
for detection in detections:

    label = detection["class"]
    confidence = detection["confidence"]

    x1, y1, x2, y2 = detection["box"]

    print(
        f"{label}: "
        f"confidence={confidence:.2f}, "
        f"box=({x1}, {y1}, {x2}, {y2})"
    )

person: confidence=0.92, box=(100, 80, 250, 400)
car: confidence=0.87, box=(350, 200, 650, 420)
dog: confidence=0.76, box=(500, 100, 620, 250)


In [2]:
import torch

print("PyTorch:", torch.__version__)
print("Torch path:", torch.__file__)
print("Has torch._utils:", hasattr(torch, "_utils"))
print("Has torch.utils:", hasattr(torch, "utils"))

PyTorch: 2.11.0+cpu
Torch path: c:\Users\Sanjarbek\maab\cv\computer-vision-roadmap\.venv\Lib\site-packages\torch\__init__.py
Has torch._utils: True
Has torch.utils: True


In [1]:
import torch
import torchvision
import torchaudio

print("Torch:", torch.__version__)
print("Torchvision:", torchvision.__version__)
print("Torchaudio:", torchaudio.__version__)

import torch._utils
print("torch._utils OK!")

Torch: 2.11.0+cpu
Torchvision: 0.26.0+cpu
Torchaudio: 2.11.0+cpu
torch._utils OK!


In [6]:
from ultralytics import YOLO

model = YOLO("yolo11n.pt")
print("YOLO READY!")

YOLO READY!


In [7]:
import requests

url = "https://ultralytics.com/images/bus.jpg"

response = requests.get(url)

with open("bus.jpg", "wb") as f:
    f.write(response.content)

In [8]:
results = model("assets/bus.jpg")


image 1/1 c:\Users\Sanjarbek\maab\cv\computer-vision-roadmap\content\08-object-detection\bus.jpg: 640x480 4 persons, 1 bus, 89.5ms
Speed: 6.0ms preprocess, 89.5ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)


In [9]:
results[0].show()

In [12]:
type(results)

list

In [14]:
results[0].save(filename="assets/detect")

'assets/detect'

In [19]:
result = results[0]

In [26]:
results

[ultralytics.engine.results.Results object with attributes:
 
 boxes: ultralytics.engine.results.Boxes object
 depth: None
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 

In [21]:
boxes = result.boxes

print(boxes)

ultralytics.engine.results.Boxes object with attributes:

cls: tensor([5., 0., 0., 0., 0.])
conf: tensor([0.9402, 0.8882, 0.8783, 0.8558, 0.6219])
data: tensor([[3.8327e+00, 2.2936e+02, 7.9619e+02, 7.2841e+02, 9.4015e-01, 5.0000e+00],
        [6.7102e+02, 3.9483e+02, 8.0981e+02, 8.7871e+02, 8.8822e-01, 0.0000e+00],
        [4.7405e+01, 3.9957e+02, 2.3930e+02, 9.0420e+02, 8.7825e-01, 0.0000e+00],
        [2.2306e+02, 4.0869e+02, 3.4447e+02, 8.6044e+02, 8.5577e-01, 0.0000e+00],
        [2.1726e-02, 5.5607e+02, 6.8885e+01, 8.7236e+02, 6.2192e-01, 0.0000e+00]])
id: None
is_track: False
orig_shape: (1080, 810)
shape: torch.Size([5, 6])
xywh: tensor([[400.0136, 478.8882, 792.3619, 499.0481],
        [740.4135, 636.7728, 138.7925, 483.8794],
        [143.3527, 651.8801, 191.8959, 504.6299],
        [283.7633, 634.5622, 121.4086, 451.7471],
        [ 34.4536, 714.2139,  68.8638, 316.2906]])
xywhn: tensor([[0.4938, 0.4434, 0.9782, 0.4621],
        [0.9141, 0.5896, 0.1713, 0.4480],
        [0.17

- data: [x1, y1, x2, y2, confidence, class_id]

```
(x1, y1)
    ┌────────────────┐
    │                │
    │     OBJECT     │
    │                │
    └────────────────┘
                 (x2,y2)
```

In [22]:
print(type(boxes))

<class 'ultralytics.engine.results.Boxes'>


In [23]:
print(boxes.xyxy)

tensor([[3.8327e+00, 2.2936e+02, 7.9619e+02, 7.2841e+02],
        [6.7102e+02, 3.9483e+02, 8.0981e+02, 8.7871e+02],
        [4.7405e+01, 3.9957e+02, 2.3930e+02, 9.0420e+02],
        [2.2306e+02, 4.0869e+02, 3.4447e+02, 8.6044e+02],
        [2.1726e-02, 5.5607e+02, 6.8885e+01, 8.7236e+02]])


In [24]:
print(boxes.conf)

tensor([0.9402, 0.8882, 0.8783, 0.8558, 0.6219])


In [25]:
for box, confidence, class_id in zip(
    boxes.xyxy,
    boxes.conf,
    boxes.cls
):
    
    x1, y1, x2, y2 = box.tolist()
    confidence = float(confidence)
    class_id = int(class_id)
    
    class_name = model.names[class_id]
    
    print(
        f"{class_name}: "
        f"confidence={confidence:.2f}, "
        f"box=({x1:.1f}, {y1:.1f}, {x2:.1f}, {y2:.1f})"
    )

bus: confidence=0.94, box=(3.8, 229.4, 796.2, 728.4)
person: confidence=0.89, box=(671.0, 394.8, 809.8, 878.7)
person: confidence=0.88, box=(47.4, 399.6, 239.3, 904.2)
person: confidence=0.86, box=(223.1, 408.7, 344.5, 860.4)
person: confidence=0.62, box=(0.0, 556.1, 68.9, 872.4)


```
                  IMAGE
                    ↓
               YOLO MODEL
                    ↓
              RAW RESULTS
                    ↓
        ┌───────────┼───────────┐
        ↓           ↓           ↓
      BOXES      CONFIDENCE    CLASS
        ↓           ↓           ↓
   [x1,y1,x2,y2]   0.92       person

In [27]:
boxes = results[0].boxes

for i in range(len(boxes)):
    box = boxes.xyxy[i]
    confidence = boxes.conf[i]
    class_id = int(boxes.cls[i])
    class_name = model.names[class_id]

    x1, y1, x2, y2 = box.tolist()

    print(f"\nDetection {i + 1}")
    print(f"  Class:      {class_name}")
    print(f"  Class ID:   {class_id}")
    print(f"  Confidence: {confidence:.4f}")
    print(f"  Box:        ({x1:.1f}, {y1:.1f}, {x2:.1f}, {y2:.1f})")


Detection 1
  Class:      bus
  Class ID:   5
  Confidence: 0.9402
  Box:        (3.8, 229.4, 796.2, 728.4)

Detection 2
  Class:      person
  Class ID:   0
  Confidence: 0.8882
  Box:        (671.0, 394.8, 809.8, 878.7)

Detection 3
  Class:      person
  Class ID:   0
  Confidence: 0.8783
  Box:        (47.4, 399.6, 239.3, 904.2)

Detection 4
  Class:      person
  Class ID:   0
  Confidence: 0.8558
  Box:        (223.1, 408.7, 344.5, 860.4)

Detection 5
  Class:      person
  Class ID:   0
  Confidence: 0.6219
  Box:        (0.0, 556.1, 68.9, 872.4)


In [28]:
result.show()

In [29]:
def calculate_iou(box_a, box_b):

    # Intersection coordinates
    x1 = max(box_a[0], box_b[0])
    y1 = max(box_a[1], box_b[1])

    x2 = min(box_a[2], box_b[2])
    y2 = min(box_a[3], box_b[3])

    # Intersection dimensions
    intersection_width = max(0, x2 - x1)
    intersection_height = max(0, y2 - y1)

    intersection_area = (
        intersection_width * intersection_height
    )

    # Box A area
    area_a = (
        (box_a[2] - box_a[0]) *
        (box_a[3] - box_a[1])
    )

    # Box B area
    area_b = (
        (box_b[2] - box_b[0]) *
        (box_b[3] - box_b[1])
    )

    # Union
    union_area = area_a + area_b - intersection_area

    # IoU
    iou = intersection_area / union_area

    return iou

In [30]:
box_a = [100, 100, 300, 300]
box_b = [150, 150, 350, 350]

iou = calculate_iou(box_a, box_b)

print(iou)

0.391304347826087


In [31]:
box_a = [100, 100, 300, 300]
box_b = [100, 100, 300, 300]

print(calculate_iou(box_a, box_b))

1.0


In [32]:
box_a = [100, 100, 200, 200]
box_b = [300, 300, 400, 400]

print(calculate_iou(box_a, box_b))

0.0


```
Predictions
     ↓
Sort by confidence
     ↓
Highest confidence → KEEP
     ↓
Calculate IoU with other boxes
     ↓
High overlap → SUPPRESS
     ↓
Next remaining box
     ↓
Final detections

### Next Part: Non-Maximum Suppression (NMS)

```
Predicted boxes
      ↓
Remove low-confidence boxes
      ↓
Sort by confidence
      ↓
Take highest-confidence box
      ↓
Keep it
      ↓
Calculate IoU with remaining boxes
      ↓
Remove boxes with high IoU
      ↓
Repeat
      ↓
Final boxes
```

- High confidence + high overlap = probably duplicate → suppress it.

In [33]:
boxes = [
    [100, 100, 300, 400],  # A
    [110, 105, 295, 395],  # B
    [120, 120, 310, 410],  # C
    [500, 500, 700, 700]   # D
]

scores = [
    0.95,
    0.89,
    0.82,
    0.80
]

In [34]:
iou_threshold = 0.5

In [35]:
def nms(boxes, scores, iou_threshold=0.5):

    boxes = np.array(boxes)
    scores = np.array(scores)

    # Sort indices by confidence, highest first
    order = scores.argsort()[::-1]

    keep = []

    while len(order) > 0:

        # Highest-confidence box
        current = order[0]

        # Keep it
        keep.append(current)

        remaining = []

        for index in order[1:]:

            iou = calculate_iou(
                boxes[current],
                boxes[index]
            )

            if iou <= iou_threshold:
                remaining.append(index)

        order = np.array(remaining)

    return keep

In [37]:
import numpy as np

boxes = [
    [100, 100, 300, 400],
    [110, 105, 295, 395],
    [120, 120, 310, 410],
    [500, 500, 700, 700]
]

scores = [
    0.95,
    0.89,
    0.82,
    0.80
]

keep = nms(
    boxes,
    scores,
    iou_threshold=0.5
)

print(keep)

[np.int64(0), np.int64(3)]


- Box 0 → KEEP
- Box 1 → REMOVE
- Box 2 → REMOVE
- Box 3 → KEEP

In [39]:
results = model("assets/bus.jpg")


image 1/1 c:\Users\Sanjarbek\maab\cv\computer-vision-roadmap\content\08-object-detection\assets\bus.jpg: 640x480 4 persons, 1 bus, 140.4ms
Speed: 3.9ms preprocess, 140.4ms inference, 2.9ms postprocess per image at shape (1, 3, 640, 480)


In [42]:
results[0].save(filename="runs/detect.png")

'runs/detect.png'

In [43]:
keep = nms(
    results[0].boxes.xyxy.tolist(),
    results[0].boxes.conf.tolist(),
    iou_threshold=0.5
)

In [44]:
keep

[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4)]

In [8]:
import cv2

face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades +
    "haarcascade_frontalface_default.xml"
)

In [14]:
image = cv2.imread("assets/people.png")

gray = cv2.cvtColor(
    image,
    cv2.COLOR_BGR2GRAY
)

In [15]:
faces = face_cascade.detectMultiScale(
    gray,
    scaleFactor=1.1,
    minNeighbors=5
)

In [16]:
for x, y, w, h in faces:

    cv2.rectangle(
        image,
        (x, y),
        (x + w, y + h),
        (0, 255, 0),
        2
    )

In [17]:
cv2.imshow("Haar Detection", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
import cv2

hog = cv2.HOGDescriptor()

In [19]:
hog.setSVMDetector(
    cv2.HOGDescriptor_getDefaultPeopleDetector()
)

In [22]:
image = cv2.imread("assets/people.png")

boxes, weights = hog.detectMultiScale(
    image,
    winStride=(8, 8),
    padding=(8, 8),
    scale=1.05
)

In [23]:
for x, y, w, h in boxes:

    cv2.rectangle(
        image,
        (x, y),
        (x + w, y + h),
        (0, 255, 0),
        2
    )

In [24]:
import cv2

face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades +
    "haarcascade_frontalface_default.xml"
)

In [26]:
image = cv2.imread("assets/people.png")

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [27]:
faces = face_cascade.detectMultiScale(
    gray,
    scaleFactor=1.1,
    minNeighbors=5
)

print(faces)

[[1250  212  254  254]
 [1354  497   62   62]
 [ 539  281  291  291]
 [ 784  544  304  304]
 [ 996  550  290  290]
 [ 251  608  324  324]]


In [28]:
for x, y, w, h in faces:
    cv2.rectangle(
        image,
        (x, y),
        (x + w, y + h),
        (0, 255, 0),
        2
    )

cv2.imshow("Faces", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
hog = cv2.HOGDescriptor()

hog.setSVMDetector(
    cv2.HOGDescriptor_getDefaultPeopleDetector()
)

In [32]:
image = cv2.imread("assets/people.png")

boxes, weights = hog.detectMultiScale(
    image,
    winStride=(8, 8),
    padding=(8, 8),
    scale=1.05
)

In [33]:
for x, y, w, h in boxes:
    cv2.rectangle(
        image,
        (x, y),
        (x + w, y + h),
        (0, 255, 0),
        2
    )

cv2.imshow("People", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [34]:
from ultralytics import YOLO

model = YOLO("yolo11n.pt")

In [37]:
results = model("assets/full_real_classroom.png")


image 1/1 c:\Users\Sanjarbek\maab\cv\computer-vision-roadmap\content\08-object-detection\assets\full_real_classroom.png: 384x640 20 persons, 4 backpacks, 1 bottle, 1 cup, 7 chairs, 1 potted plant, 4 dining tables, 1 tv, 1 laptop, 1 book, 97.4ms
Speed: 2.5ms preprocess, 97.4ms inference, 1.6ms postprocess per image at shape (1, 3, 384, 640)


In [39]:
results[0].save(filename="runs/classroom_detected.png")

'runs/classroom_detected.png'

In [40]:
result = results[0]

print(type(result))
print(result.boxes)

<class 'ultralytics.engine.results.Results'>
ultralytics.engine.results.Boxes object with attributes:

cls: tensor([ 0.,  0., 56., 24.,  0., 24.,  0.,  0., 56.,  0., 41.,  0., 24., 63.,  0., 39., 56.,  0., 56., 73.,  0., 24., 56.,  0.,  0., 62.,  0., 60., 56.,  0., 56., 60.,  0., 58., 60.,  0.,  0., 60.,  0.,  0.,  0.])
conf: tensor([0.8931, 0.8388, 0.7930, 0.7849, 0.7639, 0.7581, 0.7370, 0.7129, 0.6899, 0.6419, 0.6165, 0.6024, 0.5798, 0.5579, 0.5376, 0.5173, 0.5171, 0.5067, 0.4910, 0.4739, 0.4645, 0.4457, 0.4443, 0.4295, 0.4252, 0.4185, 0.3725, 0.3689, 0.3533, 0.3457, 0.3352, 0.3266, 0.3224, 0.3084, 0.3010, 0.2965, 0.2838, 0.2787, 0.2762,
        0.2584, 0.2512])
data: tensor([[5.2120e-01, 6.0711e+02, 3.0606e+02, 9.3375e+02, 8.9308e-01, 0.0000e+00],
        [1.1224e+03, 2.4063e+02, 1.3020e+03, 6.8125e+02, 8.3883e-01, 0.0000e+00],
        [5.4463e+02, 5.2336e+02, 7.3500e+02, 7.4027e+02, 7.9300e-01, 5.6000e+01],
        [1.3148e+03, 8.2883e+02, 1.4334e+03, 9.3961e+02, 7.8489e-01, 2.4000

In [45]:
for i in range(len(results[0].boxes)):

    class_id = int(results[0].boxes.cls[i])
    class_name = model.names[class_id]
    confidence = float(results[0].boxes.conf[i])

    print(
        class_name,
        f"{confidence:.2f}"
    )

person 0.89
person 0.84
chair 0.79
backpack 0.78
person 0.76
backpack 0.76
person 0.74
person 0.71
chair 0.69
person 0.64
cup 0.62
person 0.60
backpack 0.58
laptop 0.56
person 0.54
bottle 0.52
chair 0.52
person 0.51
chair 0.49
book 0.47
person 0.46
backpack 0.45
chair 0.44
person 0.43
person 0.43
tv 0.42
person 0.37
dining table 0.37
chair 0.35
person 0.35
chair 0.34
dining table 0.33
person 0.32
potted plant 0.31
dining table 0.30
person 0.30
person 0.28
dining table 0.28
person 0.28
person 0.26
person 0.25


In [44]:
len(results[0].boxes)

41

                 IMAGE / VIDEO
                       │
                       ▼
                ┌──────────────┐
                │ PREPROCESSING│
                └──────┬───────┘
                       │
                       ▼
              ┌─────────────────┐
              │ DETECTION MODEL │
              └────────┬────────┘
                       │
          ┌────────────┼────────────┐
          ▼            ▼            ▼
      BOUNDING BOX   CLASS       CONFIDENCE
          │            │            │
          └────────────┼────────────┘
                       ▼
              CONFIDENCE FILTER
                       │
                       ▼
                      IoU
                       │
                       ▼
                      NMS
                       │
                       ▼
               FINAL DETECTIONS
                       │
                       ▼
                DRAW / USE DATA

In [49]:
import cv2

image = cv2.imread("assets/people.png")
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

model = cv2.CascadeClassifier(
    cv2.data.haarcascades +
    "haarcascade_frontalface_default.xml"
)

boxes = model.detectMultiScale(gray)

for x, y, w, h in boxes:
    cv2.rectangle(
        image,
        (x, y),
        (x + w, y + h),
        (0, 255, 0),
        2
    )

cv2.imshow("Detection", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Full pipeline in video

In [50]:
import cv2
import time
from ultralytics import YOLO

In [51]:
model = YOLO("yolo11n.pt")

In [57]:
video_path = "assets/people-walking.mp4"
output_path = "runs/people_detected.mp4"

cap = cv2.VideoCapture(video_path)

if not cap.isOpened():
    raise RuntimeError("Could not open video")

In [58]:
fps = cap.get(cv2.CAP_PROP_FPS)
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

print(f"FPS: {fps}")
print(f"Resolution: {width}x{height}")
print(f"Frames: {frame_count}")
print(f"Duration: {frame_count / fps:.2f} sec")

FPS: 30.0
Resolution: 1920x1080
Frames: 247
Duration: 8.23 sec


In [59]:
fourcc = cv2.VideoWriter_fourcc(*"mp4v")

writer = cv2.VideoWriter(
    output_path,
    fourcc,
    fps,
    (width, height)
)

In [60]:
frame_number = 0
start_time = time.time()

while True:

    ret, frame = cap.read()

    if not ret:
        break

    frame_number += 1

    # YOLO inference
    results = model(
        frame,
        classes=[0],      # person only
        conf=0.40,
        verbose=False
    )

    result = results[0]

    # Draw detections
    annotated_frame = result.plot()

    # FPS calculation
    elapsed = time.time() - start_time

    processing_fps = frame_number / elapsed

    cv2.putText(
        annotated_frame,
        f"FPS: {processing_fps:.1f}",
        (20, 40),
        cv2.FONT_HERSHEY_SIMPLEX,
        1,
        (0, 255, 0),
        2
    )

    # Display
    cv2.imshow(
        "YOLO Person Detection",
        annotated_frame
    )

    # Save
    writer.write(annotated_frame)

    # ESC to stop
    if cv2.waitKey(1) & 0xFF == 27:
        break


cap.release()
writer.release()
cv2.destroyAllWindows()

In [61]:
import cv2
from ultralytics import YOLO

model = YOLO("yolo11n.pt")

cap = cv2.VideoCapture("assets/people-walking.mp4")

fps = cap.get(cv2.CAP_PROP_FPS)
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

writer = cv2.VideoWriter(
    "runs/people_detected_custom.mp4",
    cv2.VideoWriter_fourcc(*"mp4v"),
    fps,
    (width, height)
)

```
Image
  ↓
Backbone
  ↓
Neck
  ↓
Detection Head
  ↓
Boxes + Classes + Confidence
```

- **Backbone**: image → edges → shapes → objects/features
- **Neck**: small objects, medium objects, and large objects
- **Head**: [x1, y1, x2, y2], confidence, class

In [ ]:
results = model(source=0, show=True)

1/1: 0... Success  (inf frames of shape 640x480 at 30.00 FPS)

WARNING 
Inference results will accumulate in RAM unless `stream=True` is passed, which can cause out-of-memory errors for large
sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs



KeyboardInterrupt: 

: 

In [1]:
print('hello')

hello


In [3]:
from ultralytics import YOLO

model = YOLO("yolo11n.pt")

results = model(
    "assets/people-walking.mp4",
    classes=[0],
    conf=0.4
)


WARNING 
Inference results will accumulate in RAM unless `stream=True` is passed, which can cause out-of-memory errors for large
sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (frame 1/247) c:\Users\Sanjarbek\maab\cv\computer-vision-roadmap\content\08-object-detection\assets\people-walking.mp4: 384x640 3 persons, 85.4ms
video 1/1 (frame 2/247) c:\Users\Sanjarbek\maab\cv\computer-vision-roadmap\content\08-object-detection\assets\people-walking.mp4: 384x640 3 persons, 46.5ms
video 1/1 (frame 3/247) c:\Users\Sanjarbek\maab\cv\computer-vision-roadmap\content\08-object-detection\assets\people-walking.mp4: 384x640 3 persons, 

In [4]:
save_path = "runs/people_detected.mp4"

results[0].save(save_path)

'runs/people_detected.mp4'

```
                 MODEL EVALUATION
                       │
        ┌──────────────┴──────────────┐
        ↓                             ↓
   MODEL QUALITY                SYSTEM QUALITY
        │                             │
   Precision                       FPS
   Recall                          Latency
   F1                              GPU memory
   mAP50                           CPU usage
   mAP50-95
        │                             │
        └──────────────┬──────────────┘
                       ↓
                 FINAL SYSTEM